# Generated by Django 3.2.4 on 2022-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opassword', models.CharField(max_length=150)),
                ('Npassword', models.CharField(max_length=150)),
                ('Cpassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=40)),
                ('Msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='feedbackopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=500)),
                ('Feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='instantequiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgfrom', models.CharField(max_length=100)),
                ('msgto', models.CharField(max_length=100)),
                ('msgtitle', models.CharField(max_length=300)),
                ('msgdesc', models.TextField()),
                ('msgtime', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('isstar', models.CharField(max_length=20)),
                ('isdeleted', models.CharField(max_length=20)),
                ('msgfile', models.ImageField(null=True, upload_to='static/msgfile/')),
                ('deletebysender', models.BooleanField(default=False)),
                ('deletebyrec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='myregister',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pic', models.ImageField(upload_to='static/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='resetpasswd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ugallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdes', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='null', upload_to='static/gallery/')),
            ],
        ),
    ]
